### ISSUE TITLE
Elaboração de formulário de inscrição de estudante

### ISSUE THREAD

**Issue by cleytonbiffe** [vcnafacul/client-vcnafacul#146]
Baseado no formulário utilizado pelo cursinho UFSCar, elaborar uma lista de perguntas do formulário de inscrição, indicando quais são as respostas esperadas.

- [x] Elaborar lista de perguntas
- [x] Elaborar mockup no figma

Perguntas do formulário google do Cursinho UFSCar: https://docs.google.com/document/d/1lwQa8L2zqR0ullUBsIBp4EKcT30xRXNOsincE7WYgHo/edit?usp=sharing
https://docs.google.com/forms/d/1Vetf2SSosjXQbybwNDcnzqcxgGhYNBBSjjWL5rI4EUA/edit?ts=6664e3d1

Sugestão para o Formulário VNF (contém exemplos dos textos iniciais):
link docs: https://docs.google.com/document/d/1koLjmQq1KnFuz7FUsn4TQpYS4cb-Nni3p-oNQVersbg/edit?usp=sharing

Perguntas do formulário de inscrições do Cursinho Parceiro:

Título: [Nome do Cursinho], [Unidade] - [Nome do período de inscrição]

Instruções: 
[Texto de instruções e informações relevantes até 1500 caracteres]

[Step 0] ENDEREÇO E DADOS  PARA CONTATO [confirmação dos dados de cadastro de usuário]
(Responda nos itens seguintes os dados de endereço da sua moradia e seus dados de contato.)
- CEP (Apenas números)* [autoformatação]
- Rua/Avenida* [puxa informações do CEP]
- Número*
- Bairro* [puxa informações do CEP?]
- Cidade* [puxa informações do CEP]
- Estado* [puxa informações do CEP]
- Seu número de telefone.* [aproveitar dado do cadastro VNF, mas deixar liberado para editar]
- Número de WhatsApp [aproveitar dado do cadastro VNF, mas deixar liberado para editar, se editar atualizar dado do cadastro VNF] [VALIDAR SE NÚMERO NÃO É IGUAL AO NÚMERO DO RESPONSÁVEL]

[Step 1 - Questionário base]

[Login viabiliza a utilização das informações como: E-mail*, Nome completo*, Nome Social]
- RG*
- CPF*
- Data de nascimento* [Calcular idade no momento da inscrição]
- Local de Nascimento (cidade, estado, país)*:
> - Caixa de seleção para país
>   - Brasil [default]
>   - Outro [Abre caixa para digitar]
> - [Se país = “Brasil”] Caixa de pesquisa e seleção para estado, [Se país = “Outro”] Caixa para digitar estado ou equivalente
> - [Se país = “Brasil”] Caixa de pesquisa e seleção para cidade, [Se país = “Outro”] Caixa para digitar cidade ou equivalente
- Número de telefone de contato para emergências. Coloque aqui um número de telefone para entrarmos em contato para emergências, pode ser de sua família ou amigos próximos. [VALIDAR SE NÚMERO NÃO É IGUAL AO NÚMERO DO RESPONSÁVEL, CHECK BOX: "Não tenho telefone"]

[Step 1.1 - Complemento formulário base]

[SE idade menor que 18 anos] Dados do seu responsável legal:
- Nome completo do responsável*
- RG do responsável (apenas números)*
- CPF do responsável (apenas números)*
- Telefone do responsável (apenas números)* [VALIDAR SE NÚMERO NÃO É IGUAL AO NÚMERO DO ALUNO]

[Step 2 - Pesquisa]

- Como conheceu o Cursinho da UFSCar? (Você pode selecionar mais que uma alternativa)*
> - Amigas(os)
> - Ex-alunas(os) do cursinho da UFSCar
> - Facebook
> - Instagram
> - Internet
> - Rádio
> - Site do cursinho
> - Televisão
> - Outros

[Step 3] Questionário Socioeconômico:
(Responda as questões a seguir com clareza e sinceridade e lembre-se de que os documentos comprobatórios poderão ser solicitados no ato de matrícula, conforme previsto no Manual do Candidato.)

- Em relação à sua escolaridade (ensino fundamental e médio)*
> - Fiz toda em escola pública
> - Fiz toda em escola particular com bolsa
> - Fiz toda em escola particular sem bolsa
> - Fiz a maior parte em escola particular com bolsa
> - Fiz a maior parte em escola particular sem bolsa
> - Fiz a maior parte em escola pública e parte em escola particular com bolsa
> - Fiz a maior parte em escola pública e parte em escola particular sem bolsa
> - Sesi ou Senai

- Ano de conclusão do ensino médio regular (ano em que você concluiu ou quando irá concluir)*
> - [Lista de seleção com opções dos anos em ordem decrescente, começando com 2 anos a frente do ano atual]
> - Nunca conclui [Botão de seleção que desabilita lista de seleção]

- Qual tipo de curso de ensino médio você concluiu ou concluirá?* [Lista de seleção]
> - Ensino médio regular (comum)
> - Curso técnico (ETEC ou outros)
> - Educação de jovens e adultos (EJA)
> - Curso para magistério (antigo Curso Normal)
> - Certificação do Ensino Médio pelo Enem
> - Certificação do Ensino Médio pelo ENCCEJA

- Você já foi nosso(a) aluno(a)?
> - Sim
> - Não
- [Se sim] Qual(is) ano(s) você frequentou nosso cursinho?*
> - [Caixas de seleção com os últimos 5 anos e a opção “Outros” que abre uma caixa de digitação]

- Você já iniciou ou está frequentando algum curso superior (universidade, faculdade, instituto federal)?*
> - Não
> - Sim, mas o abandonei
> - Sim, estou cursando
> - Sim e já o concluí

- [Se Sim] Em qual instituição? [Lista de seleção]
> - ESTÁCIO
> - FACERES
> - FAMEMA
> - FATEC
> - IFSP
> - UFSCar
> - UNESP
> - UNIARA
> - UNICAMP
> - UNICEP
> - UNIP
> - UNOPAR
> - USP
> - UNIFRAN
> - Universidade Cruzeiro do Sul
> - UNICESUMAR
> - UNOESTE
> - UNINTER
> - Claretiano
> - UNILASALLE
> - Outros [Abre caixa para digitar]

- Qual sua cor ou raça?* [Lista de seleção]
> - Amarela
> - Branca
> - Indígena
> - Parda
> - Preta
> - Não sei
> - Outros [Abre caixa para digitar]

- Qual seu pertencimento étnico-racial?* [Lista de seleção]
> - Afrodescendente
> - Branco
> - Indígena
> - Oriental/Asiático
> - Não sei
> - Outros [Abre caixa para digitar]

- Sobre deficiências ou outras especificidades, especifique abaixo a(s) opção(ões) em que melhor se enquadra:* 
> - Não possuo deficiências ou outras especificidades [Botão de seleção que desabilita lista de seleção]
[Se sim, Lista de seleção]
> - Possuo deficiência motora (cadeirante ou com mobilidade reduzida)
> - Possuo deficiência auditiva, mas não utilizo a língua brasileira de sinais (Libras) para me comunicar
> - Sou surdo e utilizo a língua brasileira de sinais (Libras) para me comunicar
> - Possuo deficiência visual
> - Estou no espectro autista (TEA)
> - Possuo Transtorno do Déficit de Atenção com Hiperatividade (TDAH)
> - Tenho dislexia
> - Outros [Abre caixa para digitar]

- Qual seu estado civil?*[Lista de seleção]
> - Casada(o) (relacionamento em que duas pessoas vivam juntas, mesmo que a união não seja legalizada)
> - Separada(o) judicialmente
> - Separada(o) não judicialmente
> - Solteira(o)
> - Viúva(o)

- Tem filhos(as)?
> - Sim, tenho filhas(os)
> - Não tenho filhas(os)

- [Se sim para filhos, aparece] Quantas(os) filhas(os) você tem?*[Lista de seleção]
> - 1
> - 2
> - 3
> - 4
> - 5
> - Mais de 5

- [Se sim para filhos, aparece] Eles(as) moram com você?*
> - Sim
> - Não

- Quantas pessoas moram na sua casa, incluindo você?*
> - Moro sozinho(a) [Botão de seleção que desabilita caixa de digitação, caso a pessoa respondido que os filhos moram com ela, botão fica obrigatoriamente desabilitado]
> - número [caixa de digitação apenas números]

- [Se não selecionada a opção “Moro sozinho(a)”, aparece] Quantas pessoas de 16 anos ou mais, incluindo você, moram na casa?*
> - número [caixa de digitação apenas números]

- Quantas pessoas de 16 anos ou mais, incluindo você, possuem renda? (trabalha, recebe pensão e/ou aposentadoria)*
> - número [caixa de digitação apenas números]

- Você exerce alguma atividade remunerada?*[Lista de seleção]
> - Sim, eventualmente
> - Sim, regularmente, em tempo parcial
> - Sim, regularmente, em tempo integral
> - Não

- Se você já trabalhou ou trabalha, qual a sua profissão? 
> - Nunca trabalhei [Botão de seleção que desabilita caixa de digitação]
> - texto [Caixa de digitação]

- [Se sim para atividade remunerada, aparece] Há alguém dependente de sua renda que não mora com você ?*
> - Sim
> - Não

- Qual a sua situação de moradia e convivência doméstica?*[Lista de seleção]
> - Moro sozinha(o)
> - Moro com meus pais ou responsáveis
> - Moro com amigas(os)
> - Tenho minha própria família e meus pais moram na mesma residência
> - Tenho minha própria família e meus pais não moram na mesma residência

- Você depende financeiramente dos seus pais ou responsáveis?*
> - Sim, dependo
> - Não, não dependo

- Nome da Mãe ou responsável*
> - texto [Caixa de digitação]

- Sobre a escolaridade da sua mãe ou responsável:*[Lista de seleção]
> - Escolaridade desconhecida
> - Analfabeta / não estudou
> - Primeiro ciclo (1a. a 4a. séries) do ensino fundamental incompleto
> - Primeiro ciclo (1a. a 4a. séries) do ensino fundamental completo
> - Segundo ciclo (5a. a 8a. séries) do ensino fundamental incompleto
> - Segundo ciclo (5a. a 8a. séries) do ensino fundamental completo
> - Ensino médio incompleto
> - Ensino médio completo
> - Ensino superior (faculdade) incompleto
> - Ensino superior (faculdade) completo

- Profissão atual de sua mãe ou responsável*
> - texto [Caixa de digitação]

- Profissão que a mãe ou responsável exerceu a maior parte da vida*
> - texto [Caixa de digitação]

- Nome do Pai ou responsável*
> - texto [Caixa de digitação]

- Sobre a escolaridade do sua pai ou responsável:*[Lista de seleção]
> - Escolaridade desconhecida
> - Analfabeta / não estudou
> - Primeiro ciclo (1a. a 4a. séries) do ensino fundamental incompleto
> - Primeiro ciclo (1a. a 4a. séries) do ensino fundamental completo
> - Segundo ciclo (5a. a 8a. séries) do ensino fundamental incompleto
> - Segundo ciclo (5a. a 8a. séries) do ensino fundamental completo
> - Ensino médio incompleto
> - Ensino médio completo
> - Ensino superior (faculdade) incompleto
> - Ensino superior (faculdade) completo

- Profissão atual de seu pai ou responsável*
> - texto [Caixa de digitação]

- Profissão que o pai ou responsável exerceu a maior parte da vida*
> - texto [Caixa de digitação]

- [SE selecionadas as opções: “Moro com meus pais ou responsáveis”, “Tenho minha própria família e meus pais moram na mesma residência”, “Tenho minha própria família e meus pais não moram na mesma residência”, aparece] 
Se você mora com pessoas de sua família ou depende da renda de sua família, qual é o valor aproximado da soma da renda de todas as pessoas da família?*[Lista de seleção]
> - Até R$303,00
> - Entre R$303,01 até R$606,00
> - Entre R$606,01 até R$909,00
> - Entre R$909,01 até R$1212,00
> - Entre R$1212,01 até R$1818,00
> - Entre R$1818,01 até R$2424,00
> - Entre R$2424,01 até R$3636,00
> - Entre R$3636,01 até R$4848,00
> - Entre R$4848,01 até R$6060,00
> - Entre R$6060,01 até R$7272,00
> - Entre R$7272,01 até R$8484,00
> - Entre R$8484,01 até R$9696,00
> - Mais do que R$9696,00

[SE selecionadas as opções: “Moro sozinha(o)”, “Moro com amigas(os)”, aparece] 
- Se você mora sozinha(o) ou com amigas(os), qual é o valor aproximado da sua renda individual?*[Lista de seleção]
> - Até R$303,00
> - Entre R$303,01 até R$606,00
> - Entre R$606,01 até R$909,00
> - Entre R$909,01 até R$1212,00
> - Entre R$1212,01 até R$1818,00
> - Entre R$1818,01 até R$2424,00
> - Entre R$2424,01 até R$3636,00
> - Entre R$3636,01 até R$4848,00
> - Entre R$4848,01 até R$6060,00
> - Entre R$6060,01 até R$7272,00
> - Entre R$7272,01 até R$8484,00
> - Entre R$8484,01 até R$9696,00
> - Mais do que R$9696,00

- Qual a situação da sua moradia?*[Lista de seleção]
> - Alugada
> - Cedida/emprestada
> - Moro no local de trabalho
> - Própria, pagando financiamento
> - Própria quitada
> - Outros [Abre caixa para digitar]

- Quantos cômodos tem o local onde você mora (número de quartos, salas e cozinhas)? Não conte os banheiros.*
> - Números

- Quantos banheiros há no local onde você mora?*
> - Não tem banheiro onde eu moro [Botão de seleção que desabilita caixa de digitação]
> - Números

- Selecione todos eletrodomésticos e eletrônicos que existem na sua casa: (Você pode selecionar mais que um item)*[Caixas de seleção]
> - Ar condicionado 
> - Aspirador de pó
> - Computador de mesa
> - Computador portátil (notebook)
> - Fogão
> - Freezer
> - Geladeira
> - Home theater
> - Máquina de lavar louça
> - Máquina de lavar roupas
> - Microondas
> - Secadora de roupas
> - Smart tv ou tv 4k
> - Tablet ou iPad
> - Tanquinho
> - Tv comum

- Quantas televisões de tela plana há na sua moradia?*[Lista de seleção]
> - Não tem TV de tela plana na minha moradia
> - 1
> - 2
> - 3 ou mais

- Quantos computadores de mesa e notebooks há na sua moradia?*[Lista de seleção]
> - Não tem computador de mesa ou notebook na minha moradia
> - 1
> - 2
> - 3 ou mais

- [SE sim para TV] Seu serviço de TV é pago? Ex: Claro NET, Sky etc.*
> - Sim
> - Não

- Você possui algum serviço de Streaming? Se sim, qual ou quais? (Você pode assinalar mais do que uma opção)*
> - Não possuo [Botão de seleção que desabilita caixas de seleção]
[Caixas de seleção]
> - Amazon Prime Video
> - Disney Plus
> - Globo Play
> - HBO Max
> - Netflix
> - Star Plus
> - Outros [Abre caixa para digitar]

- Você tem acesso à internet em sua casa?*
> - Não
> - Sim, através de internet a rádio (ex: SCW)
> - Sim, através da internet cabeada e/ou wi-fi (ex: NET Claro, Vivo, internets locais)

- [SE sim para internet] Qual seria a taxa de transferência de velocidade (velocidade de download) da internet via rádio, banda larga ou fibra óptica contratada?* [Lista de seleção]
> - Não sei
> - Até 5 Mega
> - De 6 a 10 Mega
> - De 11 a 25 Mega
> - De 26 a 50 Mega
> - De 51 a 100 Mega
> - De 101 a 200 Mega
> - De 201 a 300 Mega
> - Acima de 300 Mega

- Você possui acesso à internet pelo aparelho celular (GSM, 2g, 3g, 4g)?*[Lista de seleção]
> - Não
> - Sim, apenas eventualmente por aparelho próprio
> - Sim, apenas eventualmente por aparelho de outra pessoa
> - Sim, regularmente por aparelho próprio
> - Sim, regularmente por aparelho de outra pessoa

- [SE sim para internet no celular] Se você possui acesso pelo celular, qual seria a condição de plano que você utiliza?*[Lista de seleção]
> - Pacotes limitados diários sem redes sociais ilimitadas
> - Pacotes limitados diários com redes sociais ilimitadas
> - Pacotes semanais, quinzenais ou mensais
> - Plano Controle de qualquer natureza
> - Plano pós-pago
> - Outros [Abre caixa para digitar]

- Selecione a opção mais adequada para representar o valor mensal aproximado de sua conta de energia elétrica:*[Lista de seleção]
> - Até R$20,00
> - Entre R$20,01 e R$50,00
> - Entre R$50,01 e R$100,00
> - Entre R$100,01 e R$200,00
> - Mais de R$200,00

- Selecione a opção mais adequada para representar o valor mensal aproximado de sua conta de água:*[Lista de seleção]
> - Até R$20,00
> - Entre R$20,01 e R$50,00
> - Entre R$50,01 e R$100,00
> - Entre R$100,01 e R$200,00
> - Mais de R$200,00

- Qual(is) meio(s) de transporte você pretende utilizar para poder participar de nossas aulas presenciais na UFSCar - São Carlos?*[Caixas de seleção]
> - Bicicleta
> - Carro
> - Motocicleta (moto)
> - Ônibus
> - Van fretada
> - Vou a pé 
> - Outros [Abre caixa para digitar]

**Comment by leonardondev** [comment]
Tenho a sugestão de dois sites para usar de referência para os mockups
 - https://mobbin.com/
 - https://dribbble.com/

O primeiro exige login, mas considero mais "realistas" os exemplos.
